# Generated by Django 5.1.3 on 2024-11-30 14:56

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='عنوان فوتر')),
                ('url', models.URLField(verbose_name='url فوتر')),
                ('is_active', models.BooleanField(default=True, verbose_name='آیا فعال است؟')),
            ],
            options={
                'verbose_name': 'دسته بندی محصولات در فوتر',
                'verbose_name_plural': 'دسته بندی های محصولات در فوتر',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='عنوان')),
                ('url_title', models.SlugField(max_length=225, unique=True, verbose_name='نام url محصول')),
                ('is_sub', models.BooleanField(default=False, verbose_name='آیا زیرمجموعه دارد؟')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scategory', to='product_module.category', verbose_name='زیرمجموعه')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='نام محصول')),
                ('url_title', models.CharField(default='null', max_length=300, unique=True, verbose_name='نام url محصول')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/product', verbose_name='تصویر محصول')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='توضیحات محصول')),
                ('is_active', models.BooleanField(default=False, verbose_name='آیا محصول فعال است؟')),
                ('is_delete', models.BooleanField(verbose_name='آیا محصول حذف شده است؟')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, default='', editable=False, max_length=200, unique=True)),
                ('category', models.ManyToManyField(related_name='product_categories', to='product_module.category', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['title'],
            },
        ),
    ]
