# Generated by Django 5.1 on 2024-09-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='is_read_by_admin',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='response',
        ),
    ]
